torii.diagnostics.error: Added `IndexError`
We need to derive from the core `IndexError` as well as the `ToriiSyntaxError`, the former so we can get proper iteration stoppage, and the latter so we get source reporting when unbounded slicing occurs and we want to report the diagnostic